
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moonyin-thoughts-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moonyin-thoughts
  template:
    metadata:
      labels:
        app: moonyin-thoughts
    spec:
      containers:
      - name: thoughts-front
        image: thoughts-front:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: moonyin-thoughts-service
spec:
  selector:
    app: moonyin-thoughts
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort

