/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PoetryCreatorImport } from './routes/poetryCreator'
import { Route as DreamInterpretorImport } from './routes/dreamInterpretor'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PoetryCreatorRoute = PoetryCreatorImport.update({
  id: '/poetryCreator',
  path: '/poetryCreator',
  getParentRoute: () => rootRoute,
} as any)

const DreamInterpretorRoute = DreamInterpretorImport.update({
  id: '/dreamInterpretor',
  path: '/dreamInterpretor',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dreamInterpretor': {
      id: '/dreamInterpretor'
      path: '/dreamInterpretor'
      fullPath: '/dreamInterpretor'
      preLoaderRoute: typeof DreamInterpretorImport
      parentRoute: typeof rootRoute
    }
    '/poetryCreator': {
      id: '/poetryCreator'
      path: '/poetryCreator'
      fullPath: '/poetryCreator'
      preLoaderRoute: typeof PoetryCreatorImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dreamInterpretor': typeof DreamInterpretorRoute
  '/poetryCreator': typeof PoetryCreatorRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dreamInterpretor': typeof DreamInterpretorRoute
  '/poetryCreator': typeof PoetryCreatorRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dreamInterpretor': typeof DreamInterpretorRoute
  '/poetryCreator': typeof PoetryCreatorRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dreamInterpretor' | '/poetryCreator'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dreamInterpretor' | '/poetryCreator'
  id: '__root__' | '/' | '/dreamInterpretor' | '/poetryCreator'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DreamInterpretorRoute: typeof DreamInterpretorRoute
  PoetryCreatorRoute: typeof PoetryCreatorRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DreamInterpretorRoute: DreamInterpretorRoute,
  PoetryCreatorRoute: PoetryCreatorRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dreamInterpretor",
        "/poetryCreator"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dreamInterpretor": {
      "filePath": "dreamInterpretor.tsx"
    },
    "/poetryCreator": {
      "filePath": "poetryCreator.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
